import os
print ("جاري تنزيل المكاتب الخاصة في الادة")
print("∞"*60)
os.system('pip install requests')
os.system('pip install secrets')
os.system('pip install uuid')
os.system('pip install py_compile')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install random')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install user_agent')
os.system('pip install time')
os.system('pip install colorama')
os.system('pip install secrets')
os.system('cls' if os.name == 'nt' else 'clear') 
print("≠"*60)
print("تم اكتمال جميع المكاتب الان يمكن استخدام اي اداة بدون مشكله او طلب منك تثبيت مكتبه")
